version: '3.8'

services:
  yt-dlp-ui:
    build: .
    # image: ghcr.io/alexholliz/yt-dlp-ui:latest
    container_name: yt-dlp-ui
    ports:
      - "8189:8189"
    volumes:
      - ./config:/config
      - ./downloads:/downloads
    environment:
      - TZ=America/Los_Angeles
      - PORT=8189
      - DB_PATH=/config/yt-dlp-ui.sqlite
      - DOWNLOADS_PATH=/downloads
      - COOKIES_PATH=/config/cookies.txt
      - LOG_LEVEL=debug
      - YT_DL_WORKER_CONCURRENCY=2
      # Uncomment to enable basic auth:
      # - BASIC_AUTH_USERNAME=admin
      # - BASIC_AUTH_PASSWORD=changeme
    restart: unless-stopped
